//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ccjtv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diapositivas
    {
        public int Id { get; set; }
        public string NombreDiapositiva { get; set; }
        public string Ruta { get; set; }
        public string Nivel { get; set; }
        public string Tipo { get; set; }
    }
}
